#!/bin/sh
awk ' 
function replace (name) {
  result = ""
  while("oasis query " name | getline line > 0) {
    result = result line "\n"
  }
  return substr(result, 1, length(result) - 1)
}
{while(match($0,"[$]{[^}]*}")) {
  var=substr($0,RSTART+2,RLENGTH -3);
  gsub("[$]{"var"}", replace(var))
}}1' < $1